Update MISCELLANEOUS.md
CyberDiscovery/meta pull request #13
Opened 2019-05-07 09:53 UTC by teamshortcut

Added emojis. These are currently sorted in order of when they were added; if somebody would like to logically group them (e.g. Lyne ones together) they can, but I've spent enough time on this already. Resolves #6

2019-05-07 10:08 UTC, thebeanogamer requested changes
A couple small issues, plus the need for sorting.

2019-05-07 10:08 UTC, thebeanogamer commented on MISCELLANEOUS.md
> +:blobFluffyTwitsHotChoccie: | ![](https://cdn.discordapp.com/emojis/451474199102619650.png?v=1)
Why does this still exist?

2019-05-07 10:08 UTC, thebeanogamer commented on MISCELLANEOUS.md
> +:thonkharder: | ![](https://cdn.discordapp.com/emojis/450068992762183690.png?v=1)
This is the same as :quitethoughtful:, so one can be removed.
https://github.com/CyberDiscovery/meta/blob/443faefc40514be9bb36923683661265046aa153/MISCELLANEOUS.md#L35

2019-05-07 10:08 UTC, thebeanogamer commented on MISCELLANEOUS.md
> +:smirk~1: | ![](https://cdn.discordapp.com/emojis/450068991579258880.png?v=1)
Typo

2019-05-07 10:12 UTC, thebeanogamer commented on MISCELLANEOUS.md
> +:thonkharder: | ![](https://cdn.discordapp.com/emojis/450068992762183690.png?v=1)
Correction: similar, but not the same:
:quitethoughtful: https://cdn.discordapp.com/emojis/450657080995741712.png?v=1
:thinkharder: https://cdn.discordapp.com/emojis/450068992594411521.png?v=1

2019-05-07 10:14 UTC, thebeanogamer commented on MISCELLANEOUS.md
> +:thonkharder: | ![](https://cdn.discordapp.com/emojis/450068992762183690.png?v=1)
_I guess we can keep both if you really want, but it feels redundant_

2019-05-07 10:18 UTC, teamshortcut commented
The change to the emoji name is incorrect (check the server), and the others are kind of irrelevant; this is making a list of current ones. Once this is merged, that would be the point for discussion on which ones to keep.

2019-05-07 10:22 UTC, thebeanogamer commented
Unicode conflicting with server emoji makes me cry:
![image](https://user-images.githubusercontent.com/3729048/57292692-5d1e3700-70ba-11e9-866a-d7b8d3b1fe6a.png)

2019-05-07 10:23 UTC, thebeanogamer commented
> 
> 
> The change to the emoji name is incorrect (check the server), and the others are kind of irrelevant; this is making a list of current ones. Once this is merged, that would be the point for discussion on which ones to keep.

If you'd prefer emoji issues be addressed further down the line, we can merge this now, it just seemed like a good chance to kill 2 birds with one stone.

2019-05-10 22:00 UTC, thebeanogamer approved these changes

2019-05-10 22:03 UTC, lightspeedana commented
I see no big visible issues, minor stuff can be fixed later?

2019-05-10 22:03 UTC, lightspeedana approved these changes

2019-05-10 22:05 UTC, merged