Create an issue template
CyberDiscovery/meta pull request #208
Opened 2019-05-14 12:55 UTC by ZomBMage

Create ISSUE_TEMPLATE.md with sample issue template.

2019-05-14 14:16 UTC, NicholasG04 commented
Like it, could we get one for a feature request implemented too? Replacing issue with a request?

2019-05-14 14:21 UTC, ZomBMage commented
I can make another template later for that, once I am home tonight. Thanks for the suggestion

2019-05-14 15:53 UTC, teamshortcut commented
Looks good, feature request would also be useful. Will wait until added for review.

2019-05-14 16:22 UTC, ZomBMage commented
Feature/Suggestion Request template added.

2019-05-14 16:31 UTC, teamshortcut requested changes

2019-05-14 16:31 UTC, teamshortcut commented on FEATUREREQ_TEMPLATE.md
> +### *Optional: Reasoning / Explaination:*
```suggestion
### *Reasoning / Explaination:*
```
Minor edit, otherwise looks good.

2019-05-14 16:32 UTC, teamshortcut approved these changes

2019-05-14 17:03 UTC, thebeanogamer commented
:eyes:
![Screenshot_20190514-180158](https://user-images.githubusercontent.com/3729048/57717179-8880c300-7672-11e9-916c-fe023fb9476a.jpg)

2019-05-14 17:25 UTC, NicholasG04 requested changes
'Explanation' spelt incorrectly.

2019-05-14 17:26 UTC, ZomBMage commented
That's FEATURE*REQ*, short for Feature Request. Didn't want the filename too long!

2019-05-14 17:30 UTC, NicholasG04 approved these changes
Thanks :)

2019-05-18 15:48 UTC, NicholasG04 commented
@teamshortcut @thebeanogamer can we get this merged and set up?

2019-05-18 16:23 UTC, thebeanogamer approved these changes

2019-05-18 16:23 UTC, merged