Readme rework
CyberDiscovery/meta pull request #234
Opened 2019-06-06 22:12 UTC by lightspeedana

So uh I decided to rework readme.md, partially due to some apparently confusing guidelines and to make the usage of meta clearer to members new to the server/GH; let me know if there's anything I need to change or add, as I'm sure this isn't entirely complete itself.

@thebeanogamer @teamshortcut I leave this in your hands.

2019-06-07 16:12 UTC, thebeanogamer requested changes

2019-06-07 16:12 UTC, thebeanogamer commented on README.md
> +# CD Discord Meta Repository
```suggestion
# Cyber Discovery Community Discord Meta Repository
```

2019-06-07 16:12 UTC, thebeanogamer commented on README.md
> +We understand the meta repo can be somewhat confusing, so here's exactly how to use it:
```suggestion
We understand that the meta repo can be somewhat confusing, so here's exactly how to use it:
```

2019-06-07 16:12 UTC, thebeanogamer commented on README.md
> +1. Either fork the repository or make edits to files on a separate branch in `meta`.
Only we can create branches, all other users need to use forks.

2019-06-07 16:24 UTC, lightspeedana reviewed
@thebeanogamer made changes as per.

2019-06-08 19:53 UTC, Sh3llcod3 commented
I am so sorry, I still need to fix `:readme pull` not working, let me just spin up my dev machine. :man_facepalming:

2019-06-10 18:32 UTC, teamshortcut approved these changes

2019-06-10 18:34 UTC, thebeanogamer approved these changes

2019-06-10 18:34 UTC, merged